spring:
  config:
    import: optional:aws-parameterstore:/fondant/dev/, optional:classpath:application-secret.yml
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      parameterstore:
        enabled: true
      s3:
        images-bucket: ${s3.images-bucket}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


